# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
  paths:
    include:
      - src/frontend

pool:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: src/frontend
    verbose: false

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    workingDir: src/frontend
    verbose: false
    customCommand: 'run build -- --prod'

- task: Npm@1
  displayName: 'npm test-ci'
  inputs:
    command: custom
    workingDir: src/frontend
    verbose: false
    customCommand: 'run test-ci'
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TESTS-*.xml'
  inputs:
    testResultsFiles: '**/TESTS-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/src/frontend/junit'
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from src/frontend/coverage/ToDoListApp/cobertura-coverage.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'src/frontend/coverage/ToDoListApp/cobertura-coverage.xml'
    failIfCoverageEmpty: true
